name = "storageflairlondon"
main = "src/index.js"
workers_dev = true
compatibility_date = "2025-06-12"

[[routes]]
pattern = "storage.flair.london/*"
zone_name = "flair.london"

[[routes]]
pattern = "snapshots.capcom.london"
zone_name = "capcom.london"
custom_domain = true

[observability]
enabled = true
