name = "capcom-worker"
main = "worker-vox-snapshots.js"
compatibility_date = "2025-09-02"
workers_dev = false
account_id = "8b3fed5dd481b67a898081122010dc37"

routes = [
  { pattern = "vox.capcom.london/*", zone_name = "capcom.london" },
  { pattern = "snapshots.capcom.london/*", zone_name = "capcom.london" }
]